[build]
base = "/"
command = "pnpm -F @xsai-ext-transformers/provider-playground... run build"
publish = "/playground/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
